---
title: "webademic"
author: "Nic Fox"
date: "01/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Visualise how papers are connected with an interactive network visualisation.

- each node is a paper
- you can click on a node to see more details about the paper
- you can click on a line between 2 papers to see how the papers are connected
- you can zoom in and out
- you can move nodes (papers) around

```{r import_packages, warning=FALSE, include=FALSE}
library(visNetwork)
library(tidyverse)
```

```{r import_nodes, include=FALSE}
nodes <- read_csv("nodes.csv")
```

```{r import_edges, include=FALSE}
edges <- read_csv("edges.csv")
```

```{r visualise_network, message=FALSE, echo=FALSE}
network <- visNetwork(nodes, edges) %>% 
                        visEdges(arrows = 'to') %>% 
                        visNodes(shape = "box", color = "#6b1773", font = c(color="white")) %>% 
                        visEdges(color = "black")

# save network as an html file
visSave(network, file = "network.html", background = "white")

# view network
network
```